[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://environment-direct-backend.up.railway.app"

[[redirects]]
  from = "/api/*"
  to = "https://environment-direct-backend.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://environment-direct-backend.up.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "https://environment-direct-backend.up.railway.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://environment-direct-backend.up.railway.app" 