# Configures the build and deployment for the backend service.

[[services]]
name = "backend"
builder = "docker" # Explicitly use the Docker builder
rootDir = "./backend"
# Railway will automatically use the Dockerfile in this directory. 