databases:
  - name: my-app-database
    databaseName: my_app_database_khpl
    user: my_app_database_khpl_user

services:
  - type: web
    name: Env-Direct-Backend
    env: docker
    rootDir: backend
    repo: https://github.com/kevyisagenius123/Env-Direct.git
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-app-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: green-atlas-frontend
    env: static
    rootDir: env-direct-frontend
    repo: https://github.com/kevyisagenius123/Env-Direct.git
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://env-direct-backend.onrender.com 